language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
before_script:
- time
script:
- python test_monitor_sites.py
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    secure: e9jvX4ZqymG5rv47a0Gviz/IVTpTIG3jlw/KYI8ckkGGWfdaHCyiikTw2O8l/P5UUobfekmmoHRdlahVMulbb7y6/0QUD4ShUBSBO3OCxHSNiMq53M3Njxh7VueG+Lc36vXJzVu8kjbrVyzJiuhTo9/DHGlr2xOvAh6DzI6uusCk4MBcEZZJoPY7tny2ks1D24JSlE1PH/WxIlTHX8knjQl1MhEK7CnSYK4Nu9hqGWgn7vSR2o6n3b3xOKQ0S1is8BuJ+/zSthSgcxVCja98B5jrA2UIMN//cER0bh7s0BVMwd+sBolqPu4RngzpCUCEJfMN83UTnP4nYFpbwwNFmuxI0RE/zSgXBT3jA0pyPbYtdjAmHZEFCoSiElNbDK/aFet5sARQlW1rcPLGE5t57cX+8XXP/c8nTepU5s6FK+q2ssxYJU1H7mratCS4HcpOCvSETtN5Z5wJR5GbzF7V4iRW3y1IO2F9b35zjLEJfiviR4t0CvULf99C1bMS/yyEbQS0oGEU7Io+JNNOLMdUagQA3dIYDBIRUQ4QI8i5sqdWMuvBx9sj6hYWbNKFow6T7rwSny1s3F30f9pcpzf4tvH23rY/FHC9pOtJmDQ5n7EvVVvcNRLq5u7Y8H7wGrPnweVHslokT8xBw+hug+lrhKmZPbLOSmKvlUNSppLPCbU=
