language: python
python:
 - "3.5"
install: 
  - pip install -r requirements.txt
before_script:
  - time
script: 
  - python test_monitor_sites.py
notifications:
  email:
    on_success: change
    on_failure: always
